### ISSUE TITLE
Maps unable to load

### ISSUE THREAD

**Issue by nntoan** [Smile-SA/magento2-module-map#8]
## Preconditions

Magento Version: 2.2.2

ElasticSuite Version : 2.4.x

Environment: PHP 7.1.11

Third party modules: -

## Steps to reproduce

Open store locator (Shop Search)

## Expected Result

Maps loaded successfully without any errors.

## Actual Result

![screenshot 2018-01-12 08 15 24](https://user-images.githubusercontent.com/3891429/34848062-8f692774-f771-11e7-8891-d4d314a87175.png)

Error in the console log:

```js
Uncaught RangeError: Maximum call stack size exceeded
    at new o.latLng (leaflet.js:5)
    at UiClass.<anonymous> (map.js:276)
    at Array.forEach (<anonymous>)
    at UiClass.filterMarkersByBounds (map.js:275)
    at UiClass.refreshDisplayedMarkers (map.js:249)
    at e.fire (leaflet.js:5)
    at e.panBy (leaflet.js:9)
    at e._tryAnimatedPan (leaflet.js:9)
    at e.setView (leaflet.js:9)
    at e.setZoom (leaflet.js:5)
```

**Comment by romainruaud** [comment]
Hello,

how many stores do you have ?

**Comment by nntoan** [comment]
Hi @romainruaud,

We have 4 stores at this moment.

**Comment by PascalNoisette** [comment]
Hi,

I have the same issue.

The google.maps.Geocoder seems to return a format unexpected by the [geocoder-provider](https://github.com/Smile-SA/magento2-module-map/blob/master/view/frontend/web/js/geocoder-provider/google.js) 

I am redirected to the url www.example.com/stores#4324230000,234324 which is not a invalid GPS coordinate. It should fetch something like this 43.24230000,23.4324 instead.

You might be interested in a fix we are working on in order to retrieve the correct info either from [`GeocoderResult.geometry.bounds` or from `GeocoderResult.geometry.viewport`](https://developers.google.com/maps/documentation/javascript/geocoding)

Regards,
Pascal Noisette

**Comment by delyriand** [comment]
Hi @nntoan and @PascalNoisette 

I can not reproduce the problem. Is this bug still relevant?

If so, can you give me the information provided on seller? (latitude and longitude for example)

Thank you

**Comment by nntoan** [comment]
No longer an issue for us. Thank @delyriand :+1:
