### ISSUE TITLE
FreeGeoIp.net Webservice Deprecated

### ISSUE THREAD

**Issue by careys7** [Smile-SA/magento2-module-map#9]
See the readme here: https://github.com/apilayer/freegeoip

Is there any plans to update this with the replacement? Geolocation doesn't currently work

**Comment by delyriand** [comment]
Hi @careys7 

Thank you for the feedback.
We will look to introduce a replacement 

Best regards

**Comment by delyriand** [comment]
This problem only happens if:
- we use OSM
- website is not in https 

The replacement of freegeoip requires the [creation of an account](https://ipstack.com/product) for get your api key. I added a new config into Magento for specify this api key (Stores > Configuration > Services > Smile Map > Ipstack API Key) - cf #12
